services:
  db:
    image: postgres:16
    container_name: pollagg-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pollagg
    ports:
      - "5432:5432"
    volumes:
      - pollagg_pgdata:/var/lib/postgresql/data

volumes:
  pollagg_pgdata:
